### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#1]
## Goal

Biar bisa `docker-compose up` gimana caranya?

**Comment by ahmadrosid** [comment]
Aku take over issue ini ya kak, kita bisa pakai base image dari serversideup: https://serversideup.net/open-source/docker-php/ ukuran image nya cukup kecil dan first class citizen untuk laravel.

**Comment by nafiesl** [comment]
Thank you kak @ahmadrosid. :rocket:

**Comment by nafiesl** [comment]
PR #4 sudah merge, issue ini kita close.
