### ISSUE TITLE
Nomor WhatsApp Diawali Kode Negara

### ISSUE THREAD

**Issue by tajzuhud** [buku-masjid/buku-masjid#104]
Nomor HP/WA sementara di aplikasi diharuskan diawali 08, ini berdampak terhadap link ke WhatsApp yang mengaharuskan diawali kode negara. Mohon solusinya..
![Cuplikan layar 2024-12-18 082742](https://github.com/user-attachments/assets/25ca69ea-8587-446a-88e8-5b30d08854b6)

**Comment by nafiesl** [comment]
Terima kasih infonya mas @tajzuhud. Baik, kita coba perbaiki mas.

**Comment by nafiesl** [comment]
Progress:

1. Update validasi nomor telp agar bisa menerima +62xxxx sebagai kode area
2. PR: https://github.com/buku-masjid/buku-masjid/issues/104 (merged)

Mas @tajzuhud bisa coba pull commit terbaru branch master ya.
