### ISSUE TITLE
Tombol Bulan ini tidak berfungsi dengan baik

### ISSUE THREAD

**Issue by andriawan** [buku-masjid/buku-masjid#12]
Mas @nafiesl saya coba menjelajah fitur laporan. Tujuannya agar di beranda publik bisa diterapkan fitur yang mungkin sudah ada kodenya di menu ini. Saya coba dari sisi UInya sebelum mempelajari kode logika yang menyusun UI tersebut. Saya menemukan kasus dimana ketika saya coba pilih bulan maret (pada video). Kemudian saya coba kembali ke bulan ini dengan bantuan tombol Bulan ini. Filter query month tidak berubah ke bulan ini, yang harusnya September.

https://github.com/buku-masjid/buku-masjid/assets/13099373/986fe1ac-6d90-4326-964a-d1f7f754e7bd

apakah issue ini valid? mohon penjelasannya mas @nafiesl

**Comment by nafiesl** [comment]
Wah bener mas @andriawan, valid bug ini mas. Problemnya ada di baris ini:

https://github.com/buku-masjid/buku-masjid/blob/ff4374055c01fd037a9a804387390c63fa3d4b0f/resources/views/public_reports/in_months.blade.php#L17

https://github.com/buku-masjid/buku-masjid/blob/ff4374055c01fd037a9a804387390c63fa3d4b0f/resources/views/public_reports/in_out.blade.php#L17

https://github.com/buku-masjid/buku-masjid/blob/ff4374055c01fd037a9a804387390c63fa3d4b0f/resources/views/public_reports/in_weeks.blade.php#L17

Harusnya parameter querynya begini:

```diff
- Request::all()
+ Request::except(['month', 'year'])
```

Mau bantu buat PR perbaikan kah mas @andriawan?

**Comment by andriawan** [comment]
Oke mas...saya coba PR perbaikannya...

**Comment by nafiesl** [comment]
Siap mas.

Btw makasih banyak udah bantu review fitur dan kodenya mas. Alhamdulillah.

**Comment by andriawan** [comment]
Kebetulan mau pelajari kode2nya untuk fitur di beranda publik mas...ga sengaja ketemu issue ini 😬

**Comment by andriawan** [comment]
kalau saya tambah default data sama year supaya muncul di query params gimana mas @nafiesl ?

```diff
- Request::all()
+ [ 'month' => date('m'), 'year' => date('Y') ] + Request::except(['year', 'month'])
```

**Comment by nafiesl** [comment]
> kalau saya tambah default month dan year supaya muncul di query params gimana mas @nafiesl ?
> 
> ```diff
> - Request::all()
> + [ 'month' => date('m'), 'year' => date('Y') ] + Request::except(['year', 'month'])
> ```

Kalau mau eksplisit seperti itu, bisa pakai variable `$year` dan `$month` yang sudah diparsing dari controller mas.

https://github.com/buku-masjid/buku-masjid/blob/ff4374055c01fd037a9a804387390c63fa3d4b0f/app/Http/Controllers/PublicReportController.php#L52-L54

**Comment by nafiesl** [comment]
@andriawan eh salah saya mas. Abaikan komen di atas. :pray: 

Kalau menurut saya, ngga usah dikasih default month dan year deh mas, karena ketika 2 parameter itu kosong, dia default ke current month dan year.

**Comment by andriawan** [comment]
oke mas @nafiesl ...ambil dari variabel `$month` dan `$year` aja

**Comment by nafiesl** [comment]
### Progress saat ini

1. PR #13 dari mas @andriawan sudah merged.
2. Bug sudah diperbaiki.

Task ini bisa di close.
