### ISSUE TITLE
Setup Composer Project

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#2]
## Goal

Biar bisa diinstall dengan perintah:
```
composer create-project buku-masjid/buku-masjid nama_folder
```

**Comment by ImBIOS** [comment]
Ini berarti kita harus tunduk sama semantic versioning ya? perlu bikin CHANGELOG file berarti kan mas @nafiesl ?

**Comment by nafiesl** [comment]
mas @ImBIOS, idealnya seperti itu. Tetapi untuk awal mungkin tidak pakai semantic versioning dan CHANGELOG dulu mas. Saya sendiri belum pernah bikin, ini baru ide yang mau dicoba.

Bayangan saya, ketika menjalankan perintah seperti ini, otomatis dia meng-clone dari `dev-master`:
```
composer create-project buku-masjid/buku-masjid nama_folder
```

**Comment by heripermana88** [comment]
ini bikin initial project pake composer ya mas?

**Comment by nafiesl** [comment]
Betul mas @heripermana88, tapi ini kayanya sebaiknya dikerjakan oleh maintainer repo nya ya? Sepertinya butuh akses github maintainer untuk mengaitkan repo ke packagist.

**Comment by heripermana88** [comment]
iya mas betul harus maintainer

**Comment by nafiesl** [comment]
Task ini kita close, karena belum perlu. Bisa di-reopen kalau memang diperlukan.
