### ISSUE TITLE
Bug: Dobel Input Jadwal Khatib Jumat

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#24]
## Problem

Ada kejadian user menginput jadwal khatib dobel di satu hari Jumat.

![Image](https://github.com/buku-masjid/buku-masjid/assets/8721551/52c79e47-cb6f-43f8-b6fe-78935b0f701c)

## Penyebab

Saat ini tidak ada pencegahan ketika admin menginput jadwal khatib lebih dari 1 pada hari Jumat yang sama.

## Seharusnya

Tidak boleh ada 2 jadwal khatib di hari jumat yang sama.

## Cara Reproduce

1. Login sebagai admin
2. Input Jadwal Khatib di satu hari jumat
3. Input jadwal khatib lagi dengan tanggal jumat yang sama.
4. Kedua jadwal khatib tampil (seharusnya input di langkah 3 ditolak oleh sistem)

## Saran

1. Ada validasi form pada saat input dan edit jadwal khatib jika tanggal sudah digunakan pada jadwal khatib yang lain.

**Comment by azizarizaldi** [comment]
mas @nafiesl boleh saya kerjakan issue ini?

**Comment by nafiesl** [comment]
> mas @nafiesl boleh saya kerjakan issue ini?

Silakan mas @azizarizaldi, terima kasih sebelumnya mas.

**Comment by azizarizaldi** [comment]
siap mas @nafiesl izin fork yaa

**Comment by nafiesl** [comment]
Halo mas @azizarizaldi bug ini saya ambil alih ya. 

### Progress saat ini

- Pencegahan dobel jadwal khatib di tanggal yang sama dan pencegahan memilih tanggal selain hari jumat (e74cc3b6de4573b8dfddcb8d344d248b3b1e1351)

Task ini kita close.
