### ISSUE TITLE
Lengkapi template cetak laporan

### ISSUE THREAD

**Issue by utay-cugung** [buku-masjid/buku-masjid#35]
Laporan-laporan resmi keuangan sebuah lembaga/organisasi  yang berupa print out umumnya terdapat logo pada kop/header dan nama/tanda tangan ketua dan bendahara, sebagai legalitas hasil cetakan laporan keuangan yang akan di publis.

Logo juga dapat di tempelkan di bagian kiri halaman website sebagai icon lembaga dengan ukuran penyesuaian.

**Comment by utay-cugung** [comment]
Ini termasuk input struktur pengurus masjid bang, sebagai bagian dari data profil masjid.
dari penasehat,pembina,ketua sampai anggota.
Kemudian pada lembar cetak laporan, ketua dan bendahara di ambil dari data struktur tsb.

**Comment by nafiesl** [comment]
Terkait logo, sepertinya kita perlu adakan fitur upload logo di halaman profile masjid. Ini kita masukkan ke project [Fitur Web](https://github.com/orgs/buku-masjid/projects/2), tapi bagian ini perlu kita detailkan dulu requirementnya sebelum masuk ke TODO.

terima kasih masukannya, Mas @utay-cugung.

**Comment by nafiesl** [comment]
Terkait logo, kita ada sudah buatkan tasknya dan sudah ada PR on progress:
- Issue: https://github.com/buku-masjid/buku-masjid/issues/38
- PR: https://github.com/buku-masjid/buku-masjid/pull/39

**Comment by nafiesl** [comment]
## Progress saat ini

Logo sudah tampil di halaman PDF laporan keuangan masjid
- PR: #47 

## Langkah update di sistem

Untuk mendapatkan fitur ini, sistem existing dapat melakukan update dengan langkah berikut:
1. Pada file `.env` tambahkan variable baru:
    ```
    FILESYSTEM_DRIVER=public
    ```
2. Pada file `.env` pastikan variabel `APP_URL` **sesuai dengan URL web** bukumasjid masing-masing. Misal:
    ```
    APP_URL=https://demo.bukumasjid.com
    ```
3. Jalankan git pull untuk meng-update source code terbaru pada folder proyek bukumasjid
    ```
    git pull origin master
    ```
4. (Optional) Jalankan artisan optimize, jika diperlukan:
    ```
    php artisan optimize
    # atau 
    /usr/bin/php8.1 artisan optimize
    ```

## Screenshot

Ada pada deskripsi Pull Request: https://github.com/buku-masjid/buku-masjid/pull/47

**Comment by nafiesl** [comment]
Untuk selanjutnya, di sini kita perlu buat membut kolom tandantangan di cetak laporan PDF. Kita ambil contoh seperti ini.

![screen_2024-04-12_002](https://github.com/buku-masjid/buku-masjid/assets/8721551/ce098280-e22e-42c4-a987-f703327f8f17)

Keterangan:
1. Nama Kota (perlu ditambahkan pada profil masjid)
2. Tanggal Tampil sesuai kapan mencetak PDF nya
3. Teks mengetahui, ini statis saja
4. Jabatan sebelah kiri, ini bisa diatur di pengaturan per buku kas (jadi tidak harus ketua)
5. Jabatan sebelah kanan, bisa diatur di pengaturan per buku kas (tidak harus bendahara juga)
6. Nama sebelah kiri, bisa diatur di pengaturan per buku (bisa jadi tiap buku berbeda penanggung jawabnya)
7. Nama sebelah kanan, bisa diatur di pengaturan per buku (bisa jadi tiap buku berbeda penanggung jawabnya)

**Comment by utay-cugung** [comment]
Mantap. Fleksibel

**Comment by nafiesl** [comment]
Task terkait usulan ini:
- https://github.com/buku-masjid/buku-masjid/issues/68

**Comment by nafiesl** [comment]
Issue ini kita close karena fitur yang diusulkan sudah selseai dibuat. Task terkait:
- #47
- #68

Terima kasih mas @utay-cugung
