### ISSUE TITLE
Upload Logo Masjid

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#38]
## Goal

Pada task ini kita ingin membuat fitur upload logo masjid, agar bisa ditampilkan di kop cetak PDF laporan. Kurang lebih requirementnya seperti ini:
- Upload gambar dimensi bebas
- Ada fitur crop rasio 1:1 sebelum gambar diproses upload
- Ketika disimpan, gambar di-resize ke dimensi 200*200px

## Checklist

- [x] Form upload logo pada halaman edit profil masjid (buat form terpisah dari form edit profil)
- [x] Ketika pilih file, user diberikan UI untuk crop gambar dengan rasio 1:1
- [x] Simpan gambar dengan dimensi 200*200px ke storage `/storage/app/public`
- [x] Simpan ke database dalam tabel `settings`
- [x] Tampilkan logo yang sudah terupload di halaman profil masjid
- [x] Tampilkan logo yang sudah terupload di halaman edit profil masjid

## Notes:

- Untuk crop gambar sebelum upload, mungkin bisa coba https://fengyuanchen.github.io/cropperjs

## Screenshot

Halaman profil masjid dan tombol edit

![screen_2024-02-09_001](https://github.com/buku-masjid/buku-masjid/assets/8721551/c05c9aaa-cfcd-4ae4-99ac-70ebdd163d44)

**Comment by xfrends** [comment]
Assalamualaikum mas @nafiesl 
untuk image profile ini sudah saya kerjakan, tolong di review ya mas

**Comment by nafiesl** [comment]
Waalaikumussalam mas @xfrends alhamdulillah terima kasih banyak PR nya mas. Ijin saya update PRnya agar lebih informatif.

### Before 

![screen_2024-02-11_001](https://github.com/buku-masjid/buku-masjid/assets/8721551/fc5cac77-6474-486f-94aa-67202031ce16)

### After

![screen_2024-02-11_003](https://github.com/buku-masjid/buku-masjid/assets/8721551/b446ef45-2651-4001-b817-7099e07a1823)

Di sini saya update beberapa point:
1. Judul nya dibuat agar lebih informatif
2. Deskripsi menjelaskan pada PR ini kita mau ngapain, lampirkan link issue terkait, dan buat checklist apa saja yang dilakukan pada PR ini.
3. Assignee diset ke user mas @xfrends 
4. Reviewers di set ke user saya.

Selanjutnya saya review fitur dan kodenya mas.

**Comment by nafiesl** [comment]
Mas @xfrends saya ada beberapa komen di sini: 
- https://github.com/buku-masjid/buku-masjid/pull/39#pullrequestreview-1874378744
Bisa bantu perbaiki dulu ya mas.

Kemudian, di proyek ini kita mau mewajibkan ada automated testing, utamanya jika ada fitur yang mengubah isi database. Sedangkan di PR ini belum ada testingnya. Jika mas bisa, tolong ditambahkan testingnya ya. Jika belum bisa, nanti saya yang akan nambahkan.

**Comment by nafiesl** [comment]
PR #39 sudah merge, kita close task ini.
