### ISSUE TITLE
Invalid Langkah Generate Data Demo

### ISSUE THREAD

**Issue by alitaufiqfajar** [buku-masjid/buku-masjid#40]
## Detail:
Tidak berhasil generate data demo karena instruksi yang diberikan di readme tidak sesuai

![chrome_oSDewbgGfJ](https://github.com/buku-masjid/buku-masjid/assets/32703872/da42f90b-118a-411e-95d2-6cc6e2a1c0b7)

## Langkah untuk produksi error yang terjadi:
1. Akses Readme bagian panduan Data Demo
2. Copy-paste syntax ke terminal
3. jalankan perintah

![ConEmu64_93Wqja84Hh](https://github.com/buku-masjid/buku-masjid/assets/32703872/9fffb4d6-a06b-45cd-bc73-07467b8c00f5)

## Ekspektasi
Panduan untuk generate data demo sesuai dengan real di terminal sehingga pengguna dapat melakukan demo menggunakan data dummy

**Comment by nafiesl** [comment]
Terima kasih mas @alitaufiqfajar. PR nya yang #41 sudah merge.

Bisa bantu PR juga untuk yang readme.md di packagenya mas?
https://github.com/buku-masjid/demo-data?tab=readme-ov-file#cara-pakai

**Comment by nafiesl** [comment]
Update readme di package done ([981d8fc](https://github.com/buku-masjid/demo-data/commit/981d8fcb265a7081001b6f6305b8a5fc7283a994)). Issue ini bisa kita close.

Terima kasih mas @alitaufiqfajar
