### ISSUE TITLE
Gagal update rilis baru

### ISSUE THREAD

**Issue by utay-cugung** [buku-masjid/buku-masjid#45]
Gagal update rilis baru
Php artisan migrate gagal
Php composer error notif 
![IMG-20240222-WA0003](https://github.com/buku-masjid/buku-masjid/assets/155012206/45c61325-89a0-4d69-aeea-9c71c52dc4ce)

**Comment by nafiesl** [comment]
mas @utay-cugung kalau dilihat dari pesan errornya, sepertinya default PHPnya adalah versi 7.4, sehingga ketika dijalankan perintah `php` dia menjalankan php7.4. Sedangkan project bukumasjid membutuhkan PHP versi 8.1.

Solusinya: Untuk menjalankan php 8.1 di ubuntu server, bisa dicoba seperti ini mas:
```bash
/usr/bin/php8.1 artisan migrate
```
Untuk menjalankan composer:
```bash
/usr/bin/php8.1 /usr/bin/composer install
# atau
/usr/bin/php8.1 /usr/local/bin/composer install
```

**Comment by utay-cugung** [comment]
setelah mengikuti perintah di atas php versi masih tidak bisa berubah

![Uploading image.png…]()

**Comment by utay-cugung** [comment]
boleh minta petunjuknya bang
 @nafiesl

**Comment by nafiesl** [comment]
Mas @utay-cugung screenshot terbarunya belum terupload ya mas? Coba screenshot terbarunya diupload lagi mas.

**Comment by nafiesl** [comment]
Mas @utay-cugung issue ini sudah resolve ya mas. Kita close, terima kasih.
