### ISSUE TITLE
API: Endpoint Profil Masjid

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#48]
## Goal

Pada task ini kita ingin membuat satu endpoint untuk menampilkan informasi profil masjid yang bersifat publik.

### Rencana Endpoint
```
GET /api/masjid_profile
```
### Rencana Response
```
{
    "masjid_name": "Musholla Syahfitri",
    "masjid_address": "Jl. Perdagangan Komp. Bumi Indah Lestari II, RT.24/RW.02, Kuin Utara, Kec. Banjarmasin Utara, Kota Banjarmasin.",
    "google_maps_link": "https://maps.app.goo.gl/Wyj4Rc3FroayLnzv5",
    "logo_image_url": "https://demo.bukumasjid.com/storage/65ebe26735fc0.webp"
}
```

## Checklist

- [x] Membuat endpoint publik profil masjid
- [x] Response sesuai dengan rencana response diatas
- [x] Buat automated testing untuk endpoint tersebut

**Comment by muhammad-syawaldin** [comment]
Bismillaah... Izin ngerjain issue ini mas...

**Comment by nafiesl** [comment]
### Progress Saat Ini

1. @muhammad-syawaldin submit PR #52 
2. @nafiesl review PR #52 

### Selanjutnya

1. @muhammad-syawaldin perbaiki minor change request https://github.com/buku-masjid/buku-masjid/pull/52#pullrequestreview-1941356758

**Comment by nafiesl** [comment]
## Progress saat ini

1. PR #52 sudah di merge

Task ini bisa kita close. terima kasih mas @muhammad-syawaldin :pray:
