### ISSUE TITLE
API: Endpoint Jadwal Pengajian

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#49]
## Goal 

Pada task ini, kita ingin membuat satu endpoint yang menampilkan jadwal pengajian pada masjid tersebut berdasarkan rentang tanggal yang dipilih

### Rencana Endpoint

```
GET /api/schedules
```

### Rencana Response

```json
{
    "friday": [
        {
            "id": "",
            "audience_code": "",
            "date": "",
            "start_time": "",
            "end_time": "",
            "time_text": "",
            "lecturer_name": "",
            "muadzin_name": "",
            "imam_name": "",
            "title": "",
            "book_title": "",
            "book_writer": "",
            "book_link": "",
            "video_link": "",
            "audio_link": "",
            "description": "",
            "is_off": "",
            "created_at": "",
            "updated_at": ""
        }
    ],
    "public": [],
    "muslimah": [],
    "tarawih": []
}
```

## Checklist

- [x] Membuat endpoint publik jadwal
- [x] Memastikan response sesuai target response
- [x] Membuat automated testing

## Notes

1. Format endpoint dan response di atas bisa didiskusikan dulu, jika ada yang lebih optimal kita bisa terapkan.

**Comment by muhammad-syawaldin** [comment]
Bismillaah... Izin ngerjain issue ini mas...

**Comment by nafiesl** [comment]
## Progress saat ini

1. @muhammad-syawaldin submit PR #53 (saat ini sudah di-merge)

Task ini bisa kita close. terima kasih mas @muhammad-syawaldin :pray:
