### ISSUE TITLE
Bug: Terjadi error ketika edit profile masjid

### ISSUE THREAD

**Issue by pandigresik** [buku-masjid/buku-masjid#50]
## Problem : 

[Screencast from 15-03-24 06:08:04.webm](https://github.com/buku-masjid/buku-masjid/assets/1853475/4238b464-aee6-4571-b948-4399e573b192)

## Penyebab
User tidak memberikan nilai pada link google maps.

## Seharusnya
Ijinkan user tidak memberikan nilai pada link google maps, karena ada kemungkinan user belum mengetahui link google maps tersebut

## Cara Reproduce
Login sebagai admin
Pilih Pengaturan - Profil Masjid
Kosongkan inputan google maps
Terjadi error sebagaimana di video

## Saran
Ijinkan nilai setting bernilai null, yang artinya belum diset oleh user

**Comment by nafiesl** [comment]
Terima kasih mas @pandigresik kita cek PR nya.

**Comment by nafiesl** [comment]
### Progress saat ini

1. @pandigresik submit PR #51 
2. @nafiesl review PR #51 

### Selanjutnya

1. @pandigresik perbaiki PR sesuai code review.

**Comment by nafiesl** [comment]
### Progress saat ini

1. @pandigresik sudah memperbaiki PR sesuai code review
2. PR #51 approve oleh @nafiesl dan sudah merge

Task ini kita close, terima kasih mas @pandigresik.
