### ISSUE TITLE
Halaman Detail Transaksi

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#61]
## Goal

Menindaklanjuti diskusi https://github.com/buku-masjid/buku-masjid/discussions/44, pada task ini kita ingin membuat halaman detail transaksi

## Checklist

- [x] Halaman detail transaksi dengan URL: `/transactions/{transaction}`
- [x] Tombol `Lihat Detail` transaksi pada daftar transaksi
- [x] Tombol `Lihat Detail` transaksi pada detail kategori
- [x] Struktur detail transaksi lebih kurang seperti gambar berikut

![Image](https://github.com/buku-masjid/buku-masjid/assets/8721551/04fd90ce-3253-4fec-a252-dcd0d54e51b8)

## Catatan

1. Contoh halaman detail transaksi seperti di atas: [payments/show.blade.php](https://github.com/nafiesl/free-pmo/blob/master/resources/views/payments/show.blade.php) dan [payments/partials/payment-show.blade.php](https://github.com/nafiesl/free-pmo/blob/master/resources/views/payments/partials/payment-show.blade.php
)

**Comment by mharisudin** [comment]
![Screenshot 2024-03-26 at 23 47 36](https://github.com/buku-masjid/buku-masjid/assets/107900668/3a7d5ccb-fec5-4259-8a69-64aee3061663)

**Comment by nafiesl** [comment]
Sip mas @mharisudin coba buatkan PRnya mas, nanti kita review bareng2.

**Comment by nafiesl** [comment]
Task sudah selesai dengan PR
- https://github.com/buku-masjid/buku-masjid/pull/96

Task ini bisa kita close.
