### ISSUE TITLE
Bug: Nama masjid pada halaman public tidak mengikuti pengaturan profil masjid

### ISSUE THREAD

**Issue by pandigresik** [buku-masjid/buku-masjid#65]
## Problem : 
Nama masjid pada halaman public mengikuti pengaturan pada profil masjid, namun masih mengikuti pengaturan default pada .env

[Screencast from 09-04-24 07:15:33.webm](https://github.com/buku-masjid/buku-masjid/assets/1853475/70b7c0cf-206c-4c7a-aaa5-bc03b90c3c6f)

## Seharusnya
Nama masjid pada semua halaman mengikuti pengaturan pada profil masjid

## Cara Reproduce
Login sebagai admin
Pilih Pengaturan - Profil Masjid
Ubah nama masjid
Lihat kembali halaman public, nama masjid tidak berubah

## Saran
Sesuaikan nama masjid pada halaman public seperti nama masjid pada laporan dan halaman admin

**Comment by nafiesl** [comment]
PR https://github.com/buku-masjid/buku-masjid/pull/66 sudah kita merge. Issue ini kita close. Terima kasih mas @pandigresik
