### ISSUE TITLE
Ringkasan Laporan Keuangan di Beranda Publik

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/buku-masjid#8]
## Goal

Pada task ini, kita ingin membuat satu section di halaman beranda publik untuk menunjukkan ringkasan Laporan Keuangan pada pekan ini.

Misal isinya seperti ini:

### Ringkasan Laporan Kas Pekan Ini

Saldo kas Senin, 4 September 2023: Rp. 5.000.000
**Pemasukan** hingga hari ini: Rp. 1.000.000
**Pengeluaran** hingga hari ini: Rp. 1.500.000

**Saldo kas saat ini** (8 September 2023): 4.500.000

## Checklist

- [x] Saldo kas yang dihitung adalah buku dengan ID default (lihat `config('masjid.default_book_id')`)
- [x] Saldo dihitung sejak awal pekan berjalan, total pemasukan, total pengeluaran, dan saldo saat ini
- [x] Link "Lihat Detail" mengarah ke halama laporan kas per pekan.
- [x] Gunakan komponen laravel livewire

## Screenshot

Bentuknya kira-kira seperti ini

![Image](https://user-images.githubusercontent.com/8721551/266481439-b001be0d-c1d3-44ed-8800-ef036f4693ff.jpg)

**Comment by andriawan** [comment]
Bismillah, mas @nafiesl, boleh saya coba kerjakan task ini ? saya perhatikan sekilas mirip dengan task kemarin #9

**Comment by nafiesl** [comment]
Betul mas @andriawan silakan mas, makasih banyak ini bantuannya. Saya belum sempat ngerjain karena masih fokus di dokumentasi.

**Comment by nafiesl** [comment]
### Progress saat ini

1. @andriawan buat draft PR #15 
2. @nafiesl suggest metode untuk test livewire dengan `assertSeeHtml()` untuk melihat element HTML yang tampil di komponen livewire (open discussion kalau ada metode yang lebih sip)

### Selanjutnya

1. @andriawan coba implementasi suggestion code review.
2. @nafiesl review dan suggest penamaan class, method dan view.
3. @nafiesl suggest beberapa method test yang diperlukan (case-case yang perlu diuji untuk memastikan formula sudah benar).
4. @nafiesl suggest refactor class component.

**Comment by nafiesl** [comment]
### Progress saat ini

1. PR #15 sudah di merge.

Task ini bisa dclose. Makasih banyak mas @andriawan
