### ISSUE TITLE
Tambahkan nomor halaman ketika export pdf

### ISSUE THREAD

**Issue by Masjid-Al-Hidayah** [buku-masjid/buku-masjid#83]
![image](https://github.com/user-attachments/assets/c581b3b3-4d91-47e7-b490-1afd1d7f51f5)

Request Fitur:
+ Penambahan nomor halaman ketika export pdf
+ Settingan sebagai Opsional

**Comment by nafiesl** [comment]
### Progress

1. Issue ini sudah resolved dengan PR #86 

### Screenshot

**Tampilan nomor halaman pada PDF**

![image](https://github.com/user-attachments/assets/074c8e2e-6f50-411e-94fd-0604932d1183)

**Pengaturan on/off penomoran halaman PDF**

![image](https://github.com/user-attachments/assets/32d707c3-4b63-455f-8bd2-885ab6ef8a0d)

PR #86 sudah merged, issue ini kita close. Terima kasih masukannya @Masjid-Al-Hidayah.
