### ISSUE TITLE
Installation issue Laravel

### ISSUE THREAD

**Issue by haamadh** [buku-masjid/buku-masjid#95]
Maaf, newbie here

Pada saat installation step : 'php artisan key:generate' dan 'php artisan migrate --seed' muncul seperti ini.

![image](https://github.com/user-attachments/assets/7169756b-126e-4b4a-a6e9-3a107e603f51)

Apakah ada saran?

**Comment by nafiesl** [comment]
Halo mas @haamadh, kalau dilihat dari pesan errornya, mas belum berhasil proses langkah sebelumnya, yaitu menjalankan perintah `composer install`.

Apakah ketemu error juga saat menjalankan composer install?

**Comment by haamadh** [comment]
Ok. permasalahan ternyata belum support untuk PHP8.3 jadi tidak bisa install composer install. terpaksa harus downgrade ke 8.2

Terima kasih atas responnya

**Comment by nafiesl** [comment]
Alhamdulillah, oke mas @haamadh, terima kasih infonya. Kita close issue ya.
